### ISSUE TITLE
 data_pipeline.py =====>>>>> KeyError: 'info_filename'

### ISSUE THREAD

**Issue by fz5400** [ubisoft/ubisoft-laforge-ZeroEGGS#36]
root@a3e0e4950cb6:/mnt/data/_tt_/ubisoft-laforge-ZeroEGGS/ZEGGS# python3 data_pipeline.py
This may take a little bit of time ...
Traceback (most recent call last):
  File "data_pipeline.py", line 744, in <module>
    data_pipeline(conf)
  File "data_pipeline.py", line 252, in data_pipeline
    info_filename = base_path / conf["info_filename"]
KeyError: 'info_filename'

**Comment by fz5400** [comment]
Problem Solved: 
find `./config/data_pipeline_conf_v1.json` 
change the key `inf_filename ` to `info_filename `
